const Acl = {
  TOOLBAR_ANET_READ: 'toolbar.anet.read',
  TOOLBAR_BTEST_READ: 'toolbar.btest.read',
  TOOLBAR_DFM_READ: 'toolbar.dfm.read',
  TOOLBAR_ODM_READ: 'toolbar.odm.read',
  TOOLBAR_RULES_MIGR_READ: 'toolbar.rules-migr.read',
  TOOLBAR_GLOBAL_DOCS_READ: 'toolbar.global-docs.read',
  TOOLBAR_LOCAL_DOCS_READ: 'toolbar.local-docs.read',
  TOOLBAR_JIRA_READ: 'toolbar.jira.read',
  TASK_DEPLOY: 'task.deploy',
  TASK_LIST: 'task.list',
  TASK_SEARCH: 'task.search',
  TASK_CREATE: 'task.create',
  TASK_UPDATE: 'task.update',
  TASK_SIGNOFF: 'task.signoff',
  TASK_RETURN: 'task.return',
  TASK_REJECT: 'task.reject',
  TASK_ESCALATE: 'task.escalate',
  SIGNOFFS_READ: 'signoffs.read',
  HISTORY_READ: 'history.read',
  DISCUSSION_READ: 'discussion.read',
  DISCUSSION_CREATE: 'discussion.create',
  DISCUSSION_UPDATE: 'discussion.update',
  DISCUSSION_DELETE: 'discussion.delete',
  DOCUMENT_READ: 'document.read',
  DOCUMENT_CREATE: 'document.create',
  DOCUMENT_UPDATE: 'document.update',
  DOCUMENT_DELETE: 'document.delete',
  WORKLOG_READ: 'worklog.read',
  WORKLOG_CREATE: 'worklog.create',
  WORKLOG_UPDATE: 'worklog.update',
  WORKLOG_DELETE: 'worklog.delete',
  WORKLOG_OTHERS_UPDATE: 'worklog.others.update',
  WORKLOG_OTHERS_DELETE: 'worklog.others.delete',
  REPORTS_READ: 'reports.read',
  REPORTS_GENERATE: 'reports.generate',
  TASK_ID_READ: 'task.id.read',
  TASK_STEPPER_READ: 'task.stepper.read',
  TASK_NAME_READ: 'task.name.read',
  TASK_NAME_UPDATE: 'task.name.update',
  TASK_DESCRIPTION_READ: 'task.description.read',
  TASK_DESCRIPTION_UPDATE: 'task.description.update',
  TASK_PRODUCTION_CLAIM_EXAMPLE_READ: 'task.production-claim-example.read',
  TASK_PRODUCTION_CLAIM_EXAMPLE_UPDATE: 'task.production-claim-example.update',
  TASK_MODEL_DESIGN_CHANGES_READ: 'task.model-design-changes.read',
  TASK_MODEL_DESIGN_CHANGES_UPDATE: 'task.model-design-changes.update',
  TASK_DECISION_TABLE_CHANGES_READ: 'task.decision-table-changes.read',
  TASK_DECISION_TABLE_CHANGES_UPDATE: 'task.decision-table-changes.update',
  TASK_MODEL_BRANCH_URL_READ: 'task.model-branch-url.read',
  TASK_MODEL_BRANCH_URL_UPDATE: 'task.model-branch-url.update',
  TASK_DT_BRANCH_URL_READ: 'task.dt-branch-url.read',
  TASK_DT_BRANCH_URL_UPDATE: 'task.dt-branch-url.update',
  TASK_REQUIRES_ANET_CHANGES_READ: 'task.requires-anet-changes.read',
  TASK_REQUIRES_ANET_CHANGES_UPDATE: 'task.requires-anet-changes.update',
  TASK_REQUIRES_DT_CHANGES_READ: 'task.requires-dt-changes.read',
  TASK_REQUIRES_DT_CHANGES_UPDATE: 'task.requires-dt-changes.update',
  TASK_DEPENDENCY_DETAILS_READ: 'task.dependency-details.read',
  TASK_DEPENDENCY_DETAILS_UPDATE: 'task.dependency-details.update',
  TASK_TEST_NOTES_READ: 'task.test-notes.read',
  TASK_TEST_NOTES_UPDATE: 'task.test-notes.update',
  TASK_LEGACY_RULE_READ: 'task.legacy-rule.read',
  TASK_LEGACY_RULE_UPDATE: 'task.legacy-rule.update',
  TASK_LEGACY_RULE_ARCHIVED_DATE_READ: 'task.legacy-rule-archived-date.read',
  TASK_LEGACY_RULE_ARCHIVED_DATE_UPDATE:
    'task.legacy-rule-archived-date.update',
  TASK_LEGACY_TASK_READ: 'task.legacy-task.read',
  TASK_LEGACY_TASK_UPDATE: 'task.legacy-task.update',
  TASK_JIRA_ISSUE_READ: 'task.jira-issue.read',
  TASK_JIRA_ISSUE_UPDATE: 'task.jira-issue.update',
  TASK_DEPLOYMENT_DATE_READ: 'task.deployment-date.read',
  TASK_DEPLOYMENT_DATE_UPDATE: 'task.deployment-date.update',
  TASK_INTERNAL_DUE_DATE_READ: 'task.internal-due-date.read',
  TASK_INTERNAL_DUE_DATE_UPDATE: 'task.internal-due-date.update',
  TASK_EXTERNAL_DUE_DATE_READ: 'task.external-due-date.read',
  TASK_EXTERNAL_DUE_DATE_UPDATE: 'task.external-due-date.update',
  TASK_ASSIGNED_TO_READ: 'task.assigned-to.read',
  TASK_ASSIGNED_TO_UPDATE: 'task.assigned-to.update',
  TASK_ORIGINATING_SYSTEM_READ: 'task.originating-system.read',
  TASK_ORIGINATING_SYSTEM_UPDATE: 'task.originating-system.update',
  TASK_ORIGINATING_SYSTEM_ID_READ: 'task.originating-system-id.read',
  TASK_ORIGINATING_SYSTEM_ID_UPDATE: 'task.originating-system-id.update',
  TASK_TASK_TYPE_READ: 'task.task-type.read',
  TASK_TASK_TYPE_UPDATE: 'task.task-type.update',
  TASK_PRIORITY_READ: 'task.priority.read',
  TASK_PRIORITY_UPDATE: 'task.priority.update',
  TASK_STATUS_READ: 'task.status.read',
  TASK_CREATED_BY_READ: 'task.created-by.read',
  TASK_CREATED_DATE_READ: 'task.created-date.read',
  TASK_LAST_MODIFIED_BY_READ: 'task.last-modified-by.read',
  TASK_LAST_MODIFIED_DATE_READ: 'task.last-modified-date.read',
  TASK_DEPARTMENT_ORIGIN_READ: 'task.department-origin.read',
  TASK_DEPARTMENT_ORIGIN_UPDATE: 'task.department-origin.update',
  BUSINESS_REQUIREMENT_ID_READ: 'business-requirement.id.read',
  BUSINESS_REQUIREMENT_ID_SEARCH: 'business-requirement.id.search',
  BUSINESS_REQUIREMENT_NAME_READ: 'business-requirement.name.read',
  BUSINESS_REQUIREMENT_NAME_UPDATE: 'business-requirement.name.update',
  BUSINESS_REQUIREMENT_DESCRIPTION_READ:
    'business-requirement.description.read',
  BUSINESS_REQUIREMENT_DESCRIPTION_UPDATE:
    'business-requirement.description.update',
  BUSINESS_REQUIREMENT_TYPE_READ: 'business-requirement.type.read',
  BUSINESS_REQUIREMENT_TYPE_UPDATE: 'business-requirement.type.update',
  BUSINESS_REQUIREMENT_RULE_REPORTING_CATEGORY_READ:
    'business-requirement.rule-reporting-category.read',
  BUSINESS_REQUIREMENT_RULE_REPORTING_CATEGORY_UPDATE:
    'business-requirement.rule-reporting-category.update',
  TASK_PRIORITY_REASON_READ: 'task.priority-reason.read',
  TASK_PRIORITY_REASON_UPDATE: 'task.priority-reason.update',
  TASK_PRIORITY_REASON_NOTE_READ: 'task.priority-reason-note.read',
  TASK_PRIORITY_REASON_NOTE_UPDATE: 'task.priority-reason-note.update',
  BUSINESS_REQUIREMENT_SCRUB_TYPE_READ: 'business-requirement.scrub-type.read',
  BUSINESS_REQUIREMENT_SCRUB_TYPE_UPDATE:
    'business-requirement.scrub-type.update',
  BUSINESS_REQUIREMENT_CLAIM_RULE_CATEGORY_READ:
    'business-requirement.claim-rule-category.read',
  BUSINESS_REQUIREMENT_CLAIM_RULE_CATEGORY_UPDATE:
    'business-requirement.claim-rule-category.update',
  BUSINESS_REQUIREMENT_CONTEXT_READ: 'business-requirement.context.read',
  BUSINESS_REQUIREMENT_CONTEXT_UPDATE: 'business-requirement.context.update',
  BUSINESS_REQUIREMENT_LOCAL_RULE_USECASE_READ:
    'business-requirement.local-rule-usecase.read',
  BUSINESS_REQUIREMENT_LOCAL_RULE_USECASE_UPDATE:
    'business-requirement.local-rule-usecase.update',
  BUSINESS_REQUIREMENT_RULE_ENGINE_READ:
    'business-requirement.rule-engine.read',
  BUSINESS_REQUIREMENT_RULE_ENGINE_UPDATE:
    'business-requirement.rule-engine.update',
  BUSINESS_REQUIREMENT_RULE_TYPE_READ: 'business-requirement.rule-type.read',
  BUSINESS_REQUIREMENT_RULE_TYPE_UPDATE:
    'business-requirement.rule-type.update',
  BUSINESS_REQUIREMENT_VISIT_RULE_DISPLAY_LOCATION_READ:
    'business-requirement.visit-rule-display-location.read',
  BUSINESS_REQUIREMENT_VISIT_RULE_DISPLAY_LOCATION_UPDATE:
    'business-requirement.visit-rule-display-location.update',
  BUSINESS_REQUIREMENT_INTERNAL_FIX_TEXT1_READ:
    'business-requirement.internal-fix-text1.read',
  BUSINESS_REQUIREMENT_INTERNAL_FIX_TEXT1_UPDATE:
    'business-requirement.internal-fix-text1.update',
  BUSINESS_REQUIREMENT_INTERNAL_FIX_TEXT2_READ:
    'business-requirement.internal-fix-text2.read',
  BUSINESS_REQUIREMENT_INTERNAL_FIX_TEXT2_UPDATE:
    'business-requirement.internal-fix-text2.update',
  BUSINESS_REQUIREMENT_RULES2_TRANSFORMATION_STATUS_READ:
    'business-requirement.rules2-transformation-status.read',
  BUSINESS_REQUIREMENT_RULES2_TRANSFORMATION_STATUS_UPDATE:
    'business-requirement.rules2-transformation-status.update',
  BUSINESS_REQUIREMENT_UPDATE_REASONS_READ:
    'business-requirement.update-reason.read',
  BUSINESS_REQUIREMENT_UPDATE_REASONS_UPDATE:
    'business-requirement.update-reason.update',
  RATIONALIZATIONRULE_READ: 'rationalizationrule.read',
  RATIONALIZATIONRULE_CREATE: 'rationalizationrule.create',
  RATIONALIZATIONRULE_UPDATE: 'rationalizationrule.update',
  RATIONALIZATIONRULE_IMPORT: 'rationalizationrule.import',
  MIGRATIONRULE_READ: 'migrationrule.read',
  MIGRATIONRULE_CREATE: 'migrationrule.create',
  MIGRATIONRULE_UPDATE: 'migrationrule.update',
  MIGRATIONRULE_IMPORT: 'migrationrule.import',
};

export default Acl;
