const AppConstants = {
  UI_CONSTANTS: {
    COMPLETE: 'Complete',
    WHITE_SPACE: ' ',
    STAGE_ENV: 'STAGE',
    STAGE_ENV_MSG: 'Test Environment',
    WORKFLOW_REVIEW_ID: 6,
    TIMESTAMP_FORMAT: 'h:mm A',
    DATE_FORMAT: 'M/DD/YYYY',
    HISTORY_DATE_FORMAT: 'MMM DD, YYYY',
    DATE_FORMAT_WORKLOG: 'MM/DD/YYYY',
    DATE_INPUT_FORMAT: 'MM-DD-YYYY',
    DATE_WITH_TIMESTAMP_FORMAT: 'M/DD/YYYY h:mm A',
    TIME_FORMAT_REGEX: /^(((\d+(h\s))(\d+(m)))|(\d+(h))|(\d+(\m)))$/,
    ASSIGNED_TO_ME: '2',
    CREATED_BY_ME: '3',
    SIGNED_OFF_BY_ME: '4',
    ALL: '1',
    ACTIVE_TASK_TYPE: 'active-task-type',
    EVENT_SUBMIT_TASK: 1,
    EVENT_RETURN_TASK: 2,
    EVENT_REJECT_TASK: 3,
    MAX_NO_OF_SEARCH_ITEMS: 20,
    DASHBOARD_QUEUE_TAB_INDEX: {
      MY_TASK_INBOX: 0,
      READY_FOR_REVIEW: 1,
      READY_FOR_MODELING: 2,
      READY_FOR_DEV: 3,
      READY_FOR_TESTING: 4,
      READY_FOR_DEPLOYMENT: 5,
      ALL_TASKS: 10,
    },
    ORIGINATING_SYSTEM: {
      SALESFORCE: '1',
      SMARTSHEET: '2',
      JIRA: '3',
    },
    TASK_ATTRIBUTES: {
      TASK_DETAIL_ATTRIBUTES: [
        'name',
        'description',
        'testClaimExample',
        'modelDesignChanges',
        'modelBranchUrl',
        'dtBranchUrl',
        'taskDecisionTableDetails',
        'testNote',
      ],
      TASK_DECISION_TABLE_DETAILS: [
        'modelName',
        'name',
        'refId',
        'description',
        'refUrl',
      ],
      BR_DETAIL_ATTRIBUTES: [
        'businessRequirementName',
        'businessRequirementDesc',
        'businessRequirementTypeId',
        'context',
        'localRuleUseCaseId',
        'ruleReportingCategoryId',
        'ruleTypeId',
        'visitRuleDisplayLocationId',
        'internalFixText1',
        'internalFixText2',
      ],
    },
    RTE_FIELD_IDS: {
      description: 'rdw-wrapper-1',
      modelDesignChanges: 'rdw-wrapper-2',
      testNote: 'rdw-wrapper-3',
      businessRequirementDesc: 'rdw-wrapper-4',
      internalFixText1: 'rdw-wrapper-6',
      internalFixText2: 'rdw-wrapper-7',
    },
    TEXTAREA: {
      MAX_HEIGHT: '474px',
      MIN_HEIGHT: '166px',
      HEIGHT: '474px',
    },
    TASK_DEPENDENCIES: {
      DEPENDENCY_CONDITIONS: [
        { value: 'deploy with', text: 'Deploy with' },
        { value: 'blocked by', text: 'Blocked by' },
        { value: 'test with', text: 'Test with' },
      ],
      DEPENDENCY_SYSTEMS: [
        { text: 'Rule Tracker', value: '1' },
        { text: 'Jira', value: '2' },
        { text: 'Atlas', value: '3' },
      ],
      DEPENDENCY_BLOCKING_REASONS: [
        'Specific deployment date',
        'Client/Internal communication',
        'Start date equal to deployment date',
        'Impact Query',
        'CRMT',
        'LRA Updates',
      ],
      DEPENDENCY_BLOCKING_STATUS: {
        PENDING: 'Pending',
        COMPLETED: 'Completed',
      },
    },
    RIGHT_SECTION: {
      DISCUSSION_TAB_INDEX: 1,
      HISTORY_TAB_INDEX: 3,
    },
    REPORT_DATE_TYPES: [
      {
        value: 1,
        text: 'Created',
      },
      {
        value: 2,
        text: 'Closed',
      },
    ],
    PRIORITY_REASON_MANDATORY_PRIORITY_IDS: ['1', '2', '3'],
    TASK_DEPENDENCY: {
      ATLAS_ID: '3',
      JIRA_ID: '2',
      RULE_TRACKER_ID: '1',
      DEPLOY_WITH: 'deploy with',
      TEST_WITH: 'test with',
      BLOCKED_BY: 'blocked by',
      SPECIFIC_DEPLOYMENT_DATE: 'Specific deployment date',
      CLIENT_OR_INTERNAL_COMMUNICATION: 'Client/Internal communication',
      START_DATE_EQUAL_TO_DEPLOYMENT_dATE:
        'Start date equal to deployment date',
      IMPACT_QUERY: 'Impact Query',
      CRMT: 'CRMT',
      LRA_UPDATES: 'LRA Updates',
      COMPLETED: 'Completed',
      TEST_RELATED_SINGLE_TASK: 'Tested with related task ',
      TEST_RELATED_MULTI_TASK: 'Tested with related tasks ',
    },
    DEPLOY_CONFIG: {
      isAsync: true,
    },
    DUPLICATE_TASK_INFO_ACTION: {
      CREATE: 'create',
      EDIT: 'Edit',
    },
    ADVANCED_SEARCH: {
      BOOLEAN_AND: ' AND ',
      BOOLEAN_OR: ' OR ',
      GREATER_THAN_EQUALS: '>=',
      LESS_THAN_EQUALS: '<=',
      FROM: 'from',
      TO: 'to',
      CREATED_DATE: 'created date',
      DEPLOYMENT_DATE: 'deployment date',
      INTERNAL_DUE_DATE: 'internalDue date',
      CREATED_DATE_START_QUERY: 'created date >= ',
      CREATED_DATE_END_QUERY: 'created date <= ',
      CREATED_DATE_QUERY: 'created date from ',
      DEPLOYMENT_DATE_START_QUERY: 'deployment date >= ',
      DEPLOYMENT_DATE_END_QUERY: 'deployment date <= ',
      DEPLOYMENT_DATE_QUERY: 'deployment date from ',
      INTERNAL_DUE_DATE_START_QUERY: 'internalDue date >= ',
      INTERNAL_DUE_DATE_END_QUERY: 'internalDue date <= ',
      INTERNAL_DUE_DATE_QUERY: 'internalDue date from ',
      QUERY_COLUMNS: {
        searchKeyword: '',
        brName: 'BR NAME',
        brId: 'BR ID',
        taskName: 'TASK NAME',
        taskId: 'TASK ID',
        legacyRuleId: 'LEGACY RULE ID',
        modelName: 'MODEL NAME',
        DTName: 'DT NAME',
        DTId: 'DT ID',
        modelDesignChanges: 'MODEL DESIGN CHANGES',
        statusIds: 'status',
        workFlowStepIds: 'workflow step',
        assignedToIds: 'assigned to',
        signedoffByIds: 'signed off by',
        priorityIds: 'priority',
        taskTypeIds: 'task type',
      },
      NON_TEXT_FIELDS: Array.of(
        'statusIds',
        'taskTypeIds',
        'workFlowStepIds',
        'assignedToIds',
        'signedoffByIds',
        'priorityIds',
        'deploymentStartDate',
        'deploymentEndDate',
        'createdStartDate',
        'createdEndDate',
        'internalDueStartDate',
        'internalDueEndDate'
      ),
    },
    TASK_OVERVIEW: {
      EXPANDDATES: 'expandDates',
      EXPANDDETAILS: 'expandDetails',
      EXPANDLEGACYDETAILS: 'expandLegacyDetails',
      EXPANDPRIORITY: 'expandPriority',
      EXPANDPEOPLE: 'expandPeople',
    },
    RULES_MIGRATION: {
      SOURCES: {
        RULES_NOT_MIGRATED: 'RULESNOTMIGRATED',
        RULES_MIGRATED: 'RULESMIGRATED',
      },
      RULES_NOT_MIGRATED: {
        SHOWFIELDS: ['contextId', 'ruleId', 'rtTaskId'],
        UPDATEFIELDS: [
          'ruleType',
          'scrubType',
          'ordering',
          'pattern',
          'reviewerComments',
          'reviewedBy',
          'rationalizationType',
        ],
      },
      SEARCH: {
        RULELIMIT: 10,
        DATELIMIT: 'ALL',
      },
    },
  },
  SERVER_CONSTANTS: {
    PAGINATION: { ALL: 'ALL' },
    YES: 'Y',
    NO: 'N',
    PRIORITY_ID_1: '1',
    PRIORITY_NAME_0: '0',
    UNASSIGNED: 1,
    ASSIGNED_TO_ME: 1,
    PAGE_SIZE: 15,
    STATUSES: {
      BLOCKED: '8',
      REJECTED: '9',
      READY_TO_DEPLOY: '10',
      IN_PRODUCTION: '11',
      PENDING_DEPLOYMENT_DATE: '12',
    },
    WORKFLOW_STEPS: {
      ANALYZE_TASK_STEP: '1',
      REVIEW_TASK_STEP: '2',
      MANAGER_REVIEW_STEP: '3',
      MODEL_CHANGES_STEP: '4',
      MODEL_REVIEW_STEP: '9',
      CODE_CHANGES_STEP: '5',
      CODE_REVIEW_STEP: '10',
      TEST_CHANGES_STEP: '6',
      REVIEW_CHANGES_STEP: '7',
      DEPLOY_CHANGES_STEP: '8',
    },
    TASK_TYPES: {
      BUSINESS_REQUIREMENT_UPDATE: '1',
      NEW_BUSINESS_REQUIREMENT: '2',
      DUAL_MAINTENANCE_BR_UPDATE: '3',
      DUAL_MAINTENANCE_NEW_BR: '4',
    },
    REJECTION_REASON_OTHERS_ID: '8',
    GLOBAL_CONTEXT_ID: '1',
    BUSINESS_REQUIREMENT_TYPES: {
      GLOBAL: '1',
      LOCAL: '2',
      NETWORK: '3',
    },
    DEPLOYMENTS_PAGE_SIZE: 5,
    DEPARTMENT_ORIGIN_RULES_ID: '13',
    COMPLETED_STATUSES: {
      ATLAS: [
        'READY TO DEPLOY',
        'IN PRODUCTION',
        'REJECTED',
        'PENDING DEPLOYMENT DATE',
      ],
      JIRA: [
        'READY TO DEPLOY',
        'DEPLOYING',
        'DEPLOYED',
        'DONE',
        'PATCHED',
        'REJECTED',
      ],
      RULE_TRACKER: [
        'PRODPEND',
        'PATCH',
        'INPRODUCTION',
        'REJECTED',
        'COMPLETED',
      ],
    },
    AUDIT: {
      ATTRS: {
        TIMESPENT: 'timeSpent',
      },
      ATTR_GROUP: {
        TASK: [
          'taskName',
          'priority',
          'priorityReason',
          'priorityReasonNote',
          'originatingSystem',
          'originatingSystemId',
          'departmentOrigin',
          'taskType',
          'associatedLegacyRule',
          'associatedLegacyTask',
          'businessRequirementId',
          'businessRequirementName',
          'internalDueDate',
        ],
        DT: [
          'modelName',
          'decisionTableName',
          'decisionTableId',
          'decisionTableChangeDescription',
          'decisionTableLink',
        ],
        TIMEENTRY: ['timeSpent', 'workflowStep', 'loggedOn'],
        ATTACHMENT: ['documentName', 'type', 'link', 'notes'],
        TASKDEPENDENCY: [
          'type',
          'system',
          'relatedTaskId',
          'reason',
          'relatedTaskStatus',
          'date',
          'notes',
        ],
      },
    },
    CONFIG_KEYS: {
      APP_NAME: 'app.name',
      APP_ENV: 'app.environment',
      ODM_DC_URL: 'odm.dc.url',
      ODM_DC_DECISIONSERVICE_NAME: 'odm.dc.decisionservice.name',
      APP_DISABLE_CONSECUTIVE_SIGNOFF: 'app.disable.consecutive.signoff',
    },
    DEPLOYMENT_STATUSES: {
      SUCCESS: '1',
      FAILURE: '2',
      IN_PROGRESS: '3',
      COMPLETE: '4',
      REJECTED: '5',
    },
    DEPLOY_ENV_NAMES: {
      PROD_MIRROR: 'Prod-Mirror',
      PROD_US_EAST: 'Prod-East',
      PROD_US_WEST: 'Prod-West',
    },
    R2TRANSFORMATION_STATUSES: {
      UNDER_DUAL_MAINTENANCE: '1',
      IN_BACKWARD_COMPATIBLE_MODE: '2',
      COMPLETED: '3',
    },
    RTTASK_CREATION_STATUSES: {
      IN_PROGRESS: '1',
      SUCCESS: '2',
      FAILURE: '3',
    },
    REPORT_TYPES: {
      ALL_TASKS_IN_TIME_REPORT_ID: '1',
      GLOBAL_CODING_TASKS_REPORT_ID: '2',
      TAT_REPORT_ID: '3',
      TOTAL_TIME_ON_TASK_REPORT_ID: '4',
      SALESFORCE_BACKFILL_REPORT_ID: '5',
      REJECTED_TASKS_REPORT_ID: '6',
    },
    RULES_MIGRATION_TYPES: {
      MODELING: 'modeling',
      DUAL_MAINTENANCE: 'dualmaintenance',
      BACKWARD_COMPATIBILITY: 'backwardcompatibility',
      ARCHIVE: 'archive',
    },
    RULES_MIGRATION_PHASES: {
      MODELING: 'Modeling & Implementation',
      DUAL_MAINTENANCE: 'Dual Maintenance',
      BACKWARD_COMPATIBILITY: 'Backward Compatibility',
      ARCHIVE: 'Archive',
    },
  },
};

export default AppConstants;
