const Labels = {
  DASHBOARD_GRID: {
    TASK_NAME: 'Task Name',
    TASK_ID: 'Task ID',
    TASK_TYPE: 'Task Type',
    WORKFLOW_STEP: 'Workflow Step',
    STATUS: 'Status',
    ASSIGNED_TO: 'Assigned To',
    DUE_DATE: 'Due On',
    PRIORITY: 'Priority',
    BR_ID: 'BR ID',
    LEGACY_RULE_ID: '1.0 Rule ID',
    LAST_MODIFIED: 'Last Modified',
    UNASSIGNED: 'Unassigned',
    ASSIGNED_TO_ME: 'Assigned to me',
    CREATED_BY_ME: 'Created by me',
    SIGNED_OFF_BY_ME: 'Signed off by me',
    ALL: 'All',
    FILTER_BY: 'Filter by',
    ASSIGNED_TO_FILTER: 'ASSIGNEDTOFILTER',
    TASK_TYPE_FILTER: 'TASKTYPEFILTER',
    STATUS_FILTER: 'STATUSFILTER',
    WORK_FLOW_STEP_FILTER: 'WORKFLOWSTEPFILTER',
    CLEAR_ALL: 'Clear all',
  },
  DASHBOARD: {
    MY_TASK_INBOX: 'My Task Inbox',
    READY_FOR_REVIEW: 'Ready for Review',
    READY_FOR_MODELING: 'Ready for Modeling',
    READY_FOR_DEV: 'Ready for Dev',
    CREATE_TASK: 'Create Task',
    READY_FOR_TESTING: 'Ready for Testing',
    READY_FOR_DEPLOYMENT: 'Ready for Deployment',
    REPORTS: 'Reports',
  },
  MY_INBOX: {
    RUN_A_REPORT: 'Run a Report',
    VIEW_ALL_TASKS: 'View All Tasks',
  },
  CREATE_TASK: {
    NEW_TASK: 'New Task',
    TASK_NAME: 'Task Name',
    PRIORITY: 'Priority',
    PRIORITY_REASON: 'Priority Reason',
    PRIORITY_REASON_NOTE: 'Priority Reason Note',
    ORIGINATING_SYSTEM: 'Originating System',
    ORIGINATING_SYSTEM_ID: 'Originating System ID',
    DEPARTMENT_ORIGIN: 'Department Origin',
    TASK_TYPE: 'Task Type',
    LEGACY_RULE_ID: 'Associated 1.0 Rule ID',
    LEGACY_TASK_ID: 'Associated 1.0 Task',
    BUSINESS_REQUIREMENT_NAME: 'Business Requirement Name',
    BUSINESS_REQUIREMENT: 'Business Requirement',
    BUSINESS_REQUIREMENT_ID: 'Business Requirement ID',
    BR_UPDATE_REASON: 'Update Reason',
    INTERNAL_DUE_DATE: 'Internal Due Date',
    ASSIGNED_TO: 'Assigned To',
    CANCEL: 'Cancel',
    SAVE: 'Save',
  },
  PRIORITY_POLICY: {
    PRIORITY_EXPECTIONS: 'Priority Expectations',
    PRIORITY: 'Priority',
    TAT: 'TAT',
    LOCAL_RULES: 'Local Rules',
    GLOBAL_RULES: 'Global Rules',
  },
  TASK_DETAIL_FORM: {
    TASK_DETAILS: 'Task Details',
    BUSINESS_REQUIREMENT_DETAILS: 'Business Requirement Details',
    SAVE: 'Save',
    REJECT: 'Reject',
    ESCALATE: 'Escalate',
    DEESCALATE: 'De-escalate',
    REJECT_TASK: 'Reject task',
    ESCALATE_TASK: 'Escalate task',
    DEESCALATE_TASK: 'De-escalate task',
    MORE_ACTIONS: 'More actions',
    MODEL_CHANGES: 'Send For Model Changes',
    RETURN_TASK: 'Return to previous step',
    BUSINESS_REQUIREMENT_DETAILS_ARE_REQUIRED:
      'Business Requirement Details fields are required.',
    TASK_DETAILS_REQUIRED: 'Task details fields are required.',
    TASK_INFORMATION: 'Task Information',
    CHANGES: 'Changes',
    TESTING: 'Testing',
  },
  TRANSIT: {
    DEPLOYMENT_COMPLETE: 'Deployment Complete',
  },
  CONFIRM_TRANSIT: {
    ASSIGN_TO: 'Assign To',
    JIRA_STORY_ID: 'Jira Story ID',
    CANCEL: 'Cancel',
    SUBMIT: 'Submit',
  },
  RETURN_TRANSIT: {
    RETURN_TASK: 'Return Task',
    RETURN_TO: 'Return To',
    ASSIGN_TO: 'Assign To',
    REASON: 'Reason',
    CANCEL: 'Cancel',
    RETURN: 'Return',
  },
  REJECT_TRANSIT: {
    REJECT_TASK: 'Reject Task',
    REASON: 'Reason',
    DESCRIPTION: 'Description',
    CANCEL: 'Cancel',
    REJECT: 'Reject',
    VIEW_DETAILS: 'View Details',
    HIDE_DETAILS: 'Hide Details',
  },
  TASK_BASIC_DETAILS: {
    TASK_NAME: 'Task Name',
    TASK_DESCRIPTION: 'Task Description',
    MODEL_DESIGN_CHANGES: 'Model Design Changes',
    ATHENANET_CHANGES: 'athenaNet Changes',
    ODM_CHANGES: 'ODM Changes',
    CLAIM_EXAMPLE: 'Production Claim Example',
  },
  TASK_TESTING_DETAILS: {
    SECTION_TITLE: 'Testing',
    TEST_NOTE: 'Test Note',
  },
  TASK_SUMMARY: {
    OVERVIEW: 'Overview',
    DISCUSSION: 'Discussion',
    DOCUMENTS: 'Documents',
    HISTORY: 'History',
    WORK_LOG: 'My Work Log',
  },
  TASK_OVERVIEW: {
    TASK_ID: 'Task ID',
    TASK_TYPE: 'Task Type',
    PRIORITY: 'Priority',
    ASSIGNED_TO: 'Assigned To',
    CURRENT_STATUS: 'Status',
    CREATED_BY: 'Created By',
    ORIGINATING_CASE: 'Originating System ID',
    LEGACY_TASK: '1.0 Task',
    LEGACY_RULE: '1.0 Rule',
    LEGACY_RULE_ARCHIVED_DATE: '1.0 Rule Archived Date',
    JIRA_ISSUE: 'Jira Issue',
    DEPLOYMENT_DATE: 'Deployment Date',
    DEPENDENCIES_RELATED_TASK: 'Dependencies/ Related Tasks',
    LAST_MODIFIED_DATE: 'Last Modified Date',
    TASK_CREATED_DATE: 'Created Date',
    INTERNAL_DUE_DATE: 'Internal Due Date',
    CLIENT_DUE_DATE: 'External Due Date',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    ORIGINATING_SYSTEM: 'Originating System',
    DEPARTMENT_ORIGIN: 'Department Origin',
    BR_UPDATE_REASON: 'Update Reason',
    DETAILS: 'Details',
    LEGACYDETAILS: '1.0 Details',
    PEOPLE: 'People',
    DATE: 'Dates',
    REASON: 'Reason',
    PRIORITY_REASON: 'Priority Reason',
    PRIORITY_REASON_NOTE: 'Priority Reason Note',
  },
  TASK_DEPENDENCY: {
    ADD_DEPENDENCIES: 'Add Related Tasks and Dependencies',
    EDIT_DEPENDENCIES: 'Edit Dependencies',
    TYPE: 'Type',
    SYSTEM: 'System',
    STATUS: 'Status',
    TASK_ID: 'Task ID',
    NOTES: 'Notes',
    REASON: 'Reason',
    DATE: 'Date',
    CANCEL: 'Cancel',
    SAVE: 'Save',
    HEADER_TEXT_DELETE: 'Delete dependency?',
    PRIMARY_MODAL_TEXT_DELETE: 'Delete',
    MESSAGE_TEXT_DELETE: 'This action cannot be undone',
  },
  TASK_DEPENDENCY_DETAILS: {
    EXPAND: 'Expand',
    COLLAPSE: 'Collapse',
    RELATED_TASKS_AND_DEPENDENCIES: 'Related Tasks and Dependencies',
    NONE: 'None',
    ADD: 'Add',
    DEPLOYMENT_DATE: 'Deployment date: ',
  },
  TASK_DT_DETAILS: {
    DT_TEXT: 'DT-',
    DT_MODEL_NAME: 'Model Name',
    DT_NAME: 'Decision Table Name',
    DT_ID: 'Decision Table ID',
    DT_CHANGE_DESCRIPTION: 'Decision Table Change Description',
    DT_Link: 'Decision Table Link',
    GO: 'Go',
    ADD: 'Add',
    DELETE: 'Delete',
    DELETE_WITH_SPACE: 'Delete row for ',
    EXPAND_ALL: 'Expand All',
    COLLAPSE_ALL: 'Collapse All',
    DFM_LINK: 'DFM Branch Link',
    ODM_LINK: 'ODM Branch Link',
    DECISION_TABLE_CHANGES: 'Decision Table Changes',
    DELETE_WITHOUT_ID: 'Delete row ',
    DT_NO_RECORDS: 'No decision table changes added',
  },
  USER_COMMENT: {
    TODAY: 'Today',
    YESTERDAY: 'Yesterday',
  },
  TASK_SIGNOFF_DETAILS: {
    SIGNOFFS: 'Signoffs',
    WORKFLOW_STEP: 'Workflow Step',
    NEXT_ACTION_DUE: 'Next Action Due',
    SIGNED_OFF_BY: 'Signed-off-by',
    SIGNED_OFF_DATE: 'Signed-off Date',
    HYPHEN: '-',
    TXT_YES: 'y',
  },
  TASK_BUSINESS_REQUIREMENT_FIELD_LABEL: {
    BUSINESS_REQUIREMENT_ID: 'Business Requirement ID',
    BUSINESS_REQUIREMENT_NAME: 'Business Requirement Name',
    RULE_REPORTING_CATEGORY: 'Rule Reporting Category',
    DESCRIPTION: 'Business Requirement Description (Client Friendly)',
    BUSINESS_REQUIREMENT_TYPE: 'Business Requirement Type',
    CONTEXT_NAME: 'Context',
    LOCAL_RULES_USE_CASE: 'Local Rules Use Case',
    BUSINESS_REQUIREMENT_INFORMATION: 'Business Requirement Information',
    RULE_TYPE: 'Rule Type',
    VISIT_RULE_DISPLAY_LOCATION: 'Visit Rule Display Location',
    INTERNAL_FIX_TEXT1: 'Why is this rule firing?',
    INTERNAL_FIX_TEXT2: 'How does the client clear the rule?',
    INTERNAL_FIXTEXT: 'Internal FixText',
    USER_OVERRIDE_AVALIABLE: 'User Override Avaliable',
    CLAIM_RULE_CATEGORY: 'Claim Rule Category',
  },
  BUSINESS_REQUIREMENT_DETAILS: {
    BUSINESS_REQUIREMENT_INFORMATION: 'Business Requirement Information',
    BUSINESS_REQUIREMENT_ID: 'Business Requirement ID',
    BUSINESS_REQUIREMENT_NAME: 'Business Requirement Name',
    DESCRIPTION: 'Business Requirement Description (Client Friendly)',
    BUSINESS_REQUIREMENT_TYPE: 'Business Requirement Type',
    CONTEXT_NAME: 'Context',
    LOCAL_RULES_USE_CASE: 'Local Rules Use Case',
    RULE_REPORTING_CATEGORY: 'Rule Reporting Category',
    RULE_TYPE: 'Rule Type',
    VISIT_RULE_DISPLAY_LOCATION: 'Visit Rule Display Location',
    LEGACY_RULE_INFORMATION: '1.0 Rule Information',
    LEGACY_RULE_ID: '1.0 Rule ID',
    TRANSFORMATION_STATUS: 'Transformation status',
    INTERNAL_FIXTEXT: 'Internal FixText',
    INTERNAL_FIX_TEXT1: 'Why is this rule firing?',
    INTERNAL_FIX_TEXT2: 'How does the client clear the rule?',
    FUNCTIONAL_BUCKETS_AND_MODELS: 'Functional Buckets & Models',
    ASSOCIATED_TASK_DETAILS: {
      STATUS: 'Status',
      DEPLOYMENT_DATE: 'Deployment Date',
      STATUS_FILTER: 'STATUSFILTER',
      SORTASC: 'asc',
      SORTDESC: 'desc',
      HEATER_TEXT: 'Associated Tasks',
    },
  },
  DOCUMENTS: {
    HEADER_TEXT_ADD: 'Add Document',
    TEXT_ADD: 'Add Documents',
    HEADER_TEXT_EDIT: 'Edit Document',
    HEADER_TEXT_DELETE: 'Delete Document?',
    PRIMARY_MODAL_TEXT_DELETE: 'Delete',
    MESSAGE_TEXT_DELETE: 'This action cannot be undone',
    ATTACHMENTTYPE_READ_ONLY: 'Type: ',
    CREATED_BY_READ_ONLY: 'By: ',
    NOTES_READ_ONLY: 'Notes: ',
    CONTEXT_ADD: 'Add',
    CONTEXT_EDIT: 'Save',
    ICON_ADD: 'Add',
    ICON_EDIT: 'Edit',
    ICON_CLOSE: 'Close',
    ICON_DELETE: 'Delete',
    BUTTON_CANCEL: 'Cancel',
  },
  WORKLOG: {
    HEADER_TEXT_ADD: 'Log Time',
    TEXT_ADD: 'Log Time',
    HEADER_TEXT_EDIT: 'Edit Time',
    HEADER_TEXT_DELETE: 'Delete work log entry on ',
    PRIMARY_MODAL_TEXT_DELETE: 'Delete',
    MESSAGE_TEXT_DELETE: 'This action cannot be undone',
    CONTEXT_ADD: 'Add',
    CONTEXT_EDIT: 'Save',
    ICON_ADD: 'Add',
    ICON_EDIT: 'Edit',
    ICON_CLOSE: 'Close',
    ICON_DELETE: 'Delete',
    BUTTON_CANCEL: 'Cancel',
    TOTAL_TIME: 'Total Logged Time : ',
    SPENT_ON_HINT_TEXT: 'eg. 3h 30m or 45m',
    SPENT_ON_VALIDATION_TEXT:
      'Invalid Entry - Field should match the format [Eg. 3h 30m or 45m]',
    WORK_LOG_REQUIRED: 'Work log required',
    DEFAULT_ACCORDIAN_TAG: '__',
    DEFAULLT_ACCORDIAN_MESSAGE: 'No work has been logged on this task',
  },
  REPORT: {
    REPORT: 'Reports',
    REPORT_TYPE: 'Report Type',
    DATE_TYPE: 'Date Type',
    START_DATE: 'Start Date',
    END_DATE: 'End Date',
    CANCEL: 'Cancel',
    DOWNLOAD: 'Download',
  },
  DIRTYCHECKPOPUP: {
    SAVE: 'Save',
    CANCEL: 'Cancel',
    DONT: "Don't save",
    HEADING: 'Do you want to save before exiting this task ?',
    SUB_TEXT: "Your changes will be lost if you don't save them.",
  },
  COMPONENTS: {
    TEXTAREA: {
      SHOW_MORE: 'Show more',
      SHOW_LESS: 'Show less',
    },
  },
  ADVANCE_TASK_SEARCH: {
    ADD_MORE_OPTIONS: 'Add more options',
    SEARCH: 'Search',
    HAS_WORDS: 'Has words',
    BR_NAME: 'BR Name',
    BR_ID: 'BR ID',
    TASK_NAME: 'Task Name',
    TASK_ID: 'Task ID',
    LEGACY_RULE_ID: '1.0 Rule ID',
    WORKFLOW_STEP_IDS: 'Workflow Step',
    STATUS_IDS: 'Status',
    TASK_TYPE_IDS: 'Task Type',
    TO: 'to',
    CREATED_DATE: 'Created date',
    DEPLOYMENT_DATE: 'Deployment date',
    INTERNAL_DUE_DATE: 'Internal due date',
    ASSIGNED_TO_IDS: 'Assigned to',
    SIGNEDOFF_BY_IDS: 'Signed off by',
    PRIORITY_IDS: 'Priority',
    MODEL_NAME: 'Model Name',
    DT_NAME: 'DT Name',
    DT_ID: 'DT ID',
    MODEL_DESIGN_CHANGES: 'Model Design Changes',
    MULTI_PHRASE_MATCH_HINT: "Use ',' to enable AND search (ex: fhqc, fl)",
  },
  RICH_TEXT_EDITOR: {
    COLOR_PICKER: {
      TEXT_HIGHLIGHT_COLOR: 'Text Highlight Color',
      FONT_COLOR: 'Font Color',
      NO_HIGHLIGHT: 'No highlight',
      AUTOMATIC: 'Automatic',
    },
  },
  DEPLOY: {
    ENVIRONMENT: 'Environment',
    DECISION_SERVICE_NAME: 'Decision Service Name',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    TASKS_TO_DEPLOY: 'Tasks to deploy',
    DEPLOY_BTN: 'Deploy',
    PROD_RES_ENVIRONMENT: 'Production(east and west)',
    PRODMIRROR_ENVIRONMENT: 'Prodmirror',
    SIGNOFF: 'Verify deployment',
    VERIFIED_DEPLOYMENT_VERIONS:
      'The deployed version is available in US-EAST and US-WEST RES.',
    SAMPLE_REQUEST_TESTED:
      'Tested with sample request in both US-EAST and US-WEST RES.',
    RELEASE_VERSION: 'Release version',
    CANCEL: 'Cancel',
    REJECT: 'Reject',
    VERIFY: 'Verify',
    REDEPLOY: 'Re-deploy',
    COMPLETE_STATUS: 'COMPLETE',
    COMPLETED_HEADER: 'Deployment completed',
    COMPLETED_MESSAGE: 'View all deployments under deployment tab.',
    FAILED_MESSAGE: 'Deployment failed',
    RELEASE_VERSION_FORMAT_MESSAGE:
      'Must contain only digits with two .(dot) separated (ex: 21.7.4)',
    DEPLOYMENT: 'Deployment',
    DEPLOYMENTS: 'Deployments',
    REJECT_DEPLOYMENT: 'Reject Deployment',
    REASON: 'Reason',
    REJECT_FAILED: 'Reject failed',
    TASKS_AVAILABLE_TO_DEPLOY: 'Tasks available to deploy',
    DEPLOY: 'Deploy',
    DEPLOY_TASKS: 'Deploy Tasks',
    OPEN_BRACKET: '(',
    CLOSE_BRACKET: ')',
    SELECTED: 'selected',
    CREATE_DEPLOYMENT: 'Create Deployment',
    VIEW: 'View',
    IN_PROGRESS: 'In Progress',
    DEPLOYMENT_WORKLIST: 'Deployment Worklist',
  },
  DEPLOYMENT_GRID: {
    DEPLOYMENT: 'Deployment',
    STATUS: 'Status',
    TASKS: 'Tasks',
    RELEASE: 'Release',
    RELEASEDATE: 'Release date',
    RELEASEDBY: 'Released by',
    ENVIRONMENTS: 'Environments',
    RELEASED_BY: 'Released by',
    TASK: 'Task ID:',
    FILTER_BY: 'Filter by',
    ENVIRONMENT: 'Environment',
    RULE_APP_VERSION: 'Rule App version',
    ALL: 'All',
    CLEAR_ALL: 'Clear all',
    TASK_FILTER: 'TASKFILTER',
    STATUS_FILTER: 'STATUSFILTER',
    RELEASED_BY_FILTER: 'RELEASEDBYFILTER',
    TASK_FILTER_PLACEHOLDER_TEXT: 'ex: 90,120',
  },
  RULES_MIGRATION: {
    BUTTONS: {
      GO: 'Go',
      SEARCH: 'Search',
      SEARCH_PLACEHOLDER: 'Rule ID (Eg: 1.825)',
      ADD_NEW_RULE: 'Add New Rules',
      IMPORT: 'Import',
      IMPORT_TOOLTIP: 'Import CSV',
      EXPORT: 'Export',
    },
    PAGINATION: {
      DELETE: 'Delete',
      SELECTALL: 'Select All',
      UNSELECTALL: 'Unselect All',
    },
    IMPORT_RULES: {
      HEADER: 'Import Rules',
      SAVE: 'Save',
      CANCEL: 'Cancel',
      IMPORT: 'Upload via CSV',
      DOWNLOAD_SAMPLE_FORMAT: 'Download sample format',
    },
    RULES_NOT_MIGRATED: {
      HEADER: 'Rules Not Migrated',
      OBJECTIVE:
        'As we migrate rules from the Rules 1.0 engine to the 2.0 engine, we are aiming to migrate only relevant and effective rules. R&D has identified patterns of rules that may not need to be migrated and these rules have been reviewed and signed off by Business users. If an update needs to be made to one of the below rules, then the rule will need to be created in the Rules 2.0 engine. Please reach out to the Claim Readiness Rules 2.0 team before updating any of the below rules. ',
      EDIT_DIALOG: 'Edit Rules Dialog box',
      ADDNEWRULES: 'Add New Rules',
      BULK_UPLOAD: 'Bulk Upload',
      MANUAL_UPLOAD: 'Manual Upload',
      ADDRULES: 'Add Rules',
    },
    MODELING: {
      HEADER: 'Modeling And Implementation',
      OBJECTIVE:
        'These rules are actively being modeled or implemented by the R&D team. They are being monitored for any updates to 1.0 logic. If any 1.0 updates are made while the rules are in modeling or implementation, the updates will be incorporated into the 2.0 version of the rule before it is released into production.',
    },
    DUAL_MAINTENANCE: {
      HEADER: 'Dual Maintenance',
      OBJECTIVE:
        'These rules currently exists in both 1.0 and 2.0 engines and are being executed through 2.0 for some clients. Any updates being made to 1.0 logic must also be made to the 2.0 logic. Please reach out to the Claim Readiness Rules 2.0 team before updating any of the below rules.',
    },
    BACKWARD_COMPATIBILITY: {
      HEADER: 'Backward Compatibility',
      OBJECTIVE:
        'These rules are actively being used in the 1.0 and 2.0 engines. Please reach out to the Claim Readiness 2.0 team if any of these rules needs updates, as they will need to be updated in both the 1.0 and 2.0 logic.',
    },
    ARCHIVED: {
      HEADER: 'Archived - Migrated to 2.0',
      OBJECTIVE:
        'These rules have been archived in Rules 1.0 engine. This means that the rules are executing through Rules 2.0 for all clients and they are no longer being maintained in the 1.0 engine.',
    },
    COMMON: {
      PAGE_HEADER: 'Migration Worklist',
      COMMENTS: 'Comments',
      MOVE_TO_DUAL_MAINTENANCE: 'Move To Dual Maintenance',
      MOVE_TO_BACKWARD_COMPATIBILITY: 'Move To Backward Compatibility',
      MOVE_TO_ARCHIVE: 'Move To Archive',
      DUAL_MAINTENANCE_DATE: 'Dual Maintenance Start Date',
      BACKWARD_COMPATIBILITY_DATE: 'Backward Compatibility Start Date',
      ARCHIVE_DATE: 'Archive Date',
    },
    TABLE_HEADERS: {
      ID: 'ID',
      CONTEXT_ID: 'Context ID',
      RULE_ID: 'Rule ID',
      BR_ID: 'BR ID',
      RULE_TYPE: 'Rule Type',
      SCRUB_TYPE: 'Scrub Type',
      ORDERING: 'Ordering',
      PATTERN: 'Pattern',
      REVIEWER_COMMENTS: 'Reviewer Comments',
      REVIEWED_BY: 'Reviewed By',
      RT_TASK_ID: 'RT Task ID',
      RT_TASK_STATUS: 'RT Task Status',
      RATIONALIZATION_TYPE: 'Rationalization Type',
      MIGRATION_PHASE: 'Migration Phase',
      MODELING_DATE: 'Modeling Date',
      MODELING_COMMENT: 'Modeling Comment',
      DUAL_MAINTENANCE_START_DATE: 'Dual Maint. Start Date',
      BACKWARD_COMPATIBILITY_START_DATE: 'Back. Compat. Start Date',
      DUAL_MAINTENANCE_RT_TASK_ID: 'Dual Maint. RT Task',
      DUAL_MAINTENANCE_RT_TASK_STATUS: 'Dual Maint. Task Status',
      DUAL_MAINTENANCE_COMMENT: 'Dual Maint. Comment',
      ARCHIVE_DATE: 'Archived Date',
      ARCHIVE_RT_TASK_ID: 'Archived Task ID',
      ARCHIVE_RT_TASK_STATUS: 'Archived Task Status',
      ARCHIVE_COMMENT: 'Archived Comment',
      CREATED: 'Created',
      CREATED_BY: 'Created By',
      LAST_MODIFIED: 'Last Modified',
      LAST_MODIFIED_BY: 'Last Modified By',
      DELETED: 'Deleted',
      DELETED_BY: 'Deleted By',
      COMMENT: 'Comment',
    },
    SEARCH_RESULT_GRID: {
      CONTEXT_ID: 'Context ID',
      RULE_ID: 'Rule ID',
      BR_ID: 'BR ID',
      MIGRATION_STATUS: 'Migration Status',
      COMMENT: 'Comment',
    },
  },
  RT_TASK_CREATION: {
    RETRY: 'Retry',
    DISMISS: 'Dismiss',
  },
};

export default Labels;
