export const MockData = {
  TASKTYPES: [
    { id: '1', name: 'Business Requirement Update' },
    { id: '2', name: 'New Business Requirement' },
    { id: '3', name: 'Dual Update' },
    { id: '4', name: 'Global Rule Review' },
    { id: '5', name: 'GRR Rule Update' },
  ],
  QUEUETASKCOUNT: [
    { testqueuecount: '2' },
    { devqueuecount: '6' },
    { modelqueuecount: '6' },
    { reviewqueuecount: '19' },
  ],
  CLAIMRULECATEGORYLIST: [
    { id: '1', name: 'Format: Institutional', refId: '1' },
    { id: '2', name: 'Format: Professional', refId: '2' },
    { id: '3', name: 'Override:195 Override', refId: '3' },
    { id: '4', name: 'Override: Advice', refId: '4' },
    { id: '5', name: 'Override: Rule', refId: '5' },
  ],
  SCRUBTYPELIST: [
    { id: '1', name: 'NA' },
    { id: '2', name: 'Yes' },
    { id: '3', name: 'Advice' },
  ],
  PRIORITYREASONLIST: [
    { id: '1', name: 'Go Live Critical' },
    { id: '2', name: 'Impacts Client Sales' },
    { id: '3', name: 'Significant AR/ Financial Impact' },
    { id: '4', name: 'Claim Volume Impact' },
    { id: '5', name: 'Error in Production' },
  ],
  REJECTION_REASONS: [
    { id: '1', name: 'Incorrect task type' },
    { id: '2', name: 'Client changes their mind' },
    { id: '3', name: 'No responses from client' },
    { id: '4', name: 'Logic already exists' },
    { id: '5', name: 'Use athenaNet functionality' },
    { id: '6', name: 'Documentation was updated' },
    { id: '7', name: 'Compliance concern' },
    { id: '8', name: 'Other' },
  ],
  PRIORITIES: [
    {
      id: '1',
      name: '0',
      externalDueDate: '05/14/2021',
      externalTatInDays: '5',
      internalDueDate: '05/11/2021',
      internalTatInDays: '2',
    },
    {
      id: '2',
      name: '1',
      externalDueDate: '05/14/2021',
      externalTatInDays: '5',
      internalDueDate: '05/11/2021',
      internalTatInDays: '2',
    },
    {
      id: '3',
      name: '2',
      externalDueDate: '05/14/2021',
      externalTatInDays: '5',
      internalDueDate: '05/11/2021',
      internalTatInDays: '2',
    },
    {
      id: '4',
      name: '3',
      externalDueDate: '05/14/2021',
      externalTatInDays: '5',
      internalDueDate: '05/11/2021',
      internalTatInDays: '2',
    },
    {
      id: '5',
      name: '4',
      externalDueDate: '05/14/2021',
      externalTatInDays: '5',
      internalDueDate: '05/11/2021',
      internalTatInDays: '2',
    },
  ],
  ORGINATINGSYSTEMS: [
    { id: '1', name: 'Salesforce' },
    { id: '2', name: 'Smartsheet' },
    { id: '3', name: 'Jira' },
  ],
  STATUSES: [
    { id: '1', name: 'Created', workFlowStepQueueIds: null },
    { id: '2', name: 'In Queue', workFlowStepQueueIds: '2, 3, 4, 5' },
    { id: '3', name: 'Assigned', workFlowStepQueueIds: '1' },
    { id: '4', name: 'In Progress', workFlowStepQueueIds: '1, 2, 3, 4, 5' },
    { id: '9', name: 'Rejected', workFlowStepQueueIds: null },
    { id: '10', name: 'Pending Deployment', workFlowStepQueueIds: '4' },
    { id: '11', name: 'In Production', workFlowStepQueueIds: null },
  ],
  WORKFLOWSTEPS: [
    { id: '1', name: 'Analyze Task', workFlowStepQueueId: null },
    { id: '2', name: 'Review Task', workFlowStepQueueId: '2' },
    { id: '3', name: 'Manager Review', workFlowStepQueueId: '2' },
    { id: '4', name: 'Make Model Changes', workFlowStepQueueId: '3' },
    { id: '5', name: 'Make Code Changes', workFlowStepQueueId: '4' },
    { id: '6', name: 'Test Changes', workFlowStepQueueId: '5' },
    { id: '7', name: 'Review Changes', workFlowStepQueueId: '2' },
    { id: '8', name: 'Deploy Changes', workFlowStepQueueId: '4' },
  ],
  USERS: [
    {
      userName: 'aanandkumar',
      firstName: 'Anandkumar',
      lastName: 'Aniruddha Kumar',
    },
    {
      userName: 'bharini',
      firstName: 'Harini',
      lastName: 'Balaji',
    },
    {
      userName: 'jcyril',
      firstName: 'Cyril Irudayaraj',
      lastName: 'Joseph',
    },
    {
      userName: 'mmunikishore',
      firstName: 'Munikishore',
      lastName: 'Munusamy',
    },
    {
      userName: 'nsenthilkumar',
      firstName: 'Senthilkumar',
      lastName: 'Nedunchezhian',
    },
    {
      userName: 'rsubhashini',
      firstName: 'Subhashini',
      lastName: 'Ravichandran',
    },
    {
      userName: 'spremkumar',
      firstName: 'Prem Kumar',
      lastName: 'Seetharaman',
    },
    {
      userName: 'vsivachandran',
      firstName: 'Sivachandran',
      lastName: 'Vaithiyanathan',
    },
  ],
  BUSINESSREQUIREMENTTYPES: [
    { id: '1', name: 'Global' },
    { id: '2', name: 'Local' },
  ],
  RULEREPORTINGCATEGORIES: [
    { id: '1', name: 'Format: Institutional', refId: '1' },
    { id: '2', name: 'Format: Professional', refId: '2' },
    { id: '3', name: 'Override:195 Override', refId: '3' },
    { id: '4', name: 'Override: Advice', refId: '4' },
    { id: '5', name: 'Override: Rule', refId: '5' },
    { id: '6', name: 'Eligibility: Demographic', refId: '6' },
    { id: '8', name: 'Eligibility: Referral', refId: '8' },
    { id: '9', name: 'Coding: Procedure Code', refId: '9' },
    { id: '10', name: 'Validation: Provider Information', refId: '10' },
    { id: '11', name: 'Coding: Modifier', refId: '11' },
    { id: '12', name: 'Validation: Missing/Invalid Claim Data', refId: '12' },
    { id: '13', name: 'Validation: Patient Insurance Issues', refId: '13' },
  ],
  CONTEXTS: [
    { id: '60', name: 'RI - East Greenwich Pediatrics', refId: '90' },
    { id: '61', name: 'OH - Ramon Malaya, MD', refId: '91' },
    { id: '62', name: 'MA - Rifat Dweik, MD', refId: '92' },
    { id: '63', name: 'CA - East Bay Internal Medicine', refId: '93' },
  ],
  LOCALRULEUSECASES: [
    { id: '1', name: 'BCBS routing' },
    { id: '2', name: 'Capitation' },
    { id: '3', name: 'Client-specific pre-claim workflow' },
    { id: '4', name: 'Coding automation: custom solutions' },
    { id: '5', name: 'Coding automation: hospital' },
  ],
  RULEENGINES: [
    { name: 'BILLING', id: '1', description: null },
    { name: 'UNPOSTABLE', id: '2', description: null },
    { name: 'POSTING', id: '3', description: null },
    { name: 'CLAIMRES', id: '4', description: null },
    { name: 'PATIENT', id: '5', description: null },
    { name: 'ENROLLMENT', id: '6', description: null },
    { name: 'VISIT', id: '7', description: null },
    { name: 'CHECKNUMBERPARSER', id: '8', description: null },
  ],
  RULETYPES: [
    { name: 'CLAIM', id: '1', description: null },
    { name: 'CHARGE', id: '2', description: null },
    { name: 'CLAIMCREATE', id: '3', description: null },
    { name: 'TRANSACTION', id: '4', description: null },
    { name: 'CLAIMSETTING', id: '5', description: null },
  ],
  VISITRULEDISPLAYLOCATIONS: [
    { name: 'VISITBILL_BILLINGCODES', id: '1', description: null },
    { name: 'VISITBILL_MEDICALCODES', id: '2', description: null },
    { name: 'VISITBILL_CHARGES', id: '3', description: null },
    { name: 'VISITBILL_CHARGES1', id: '4', description: null },
    { name: 'VISITBILL_CHARGES2', id: '5', description: null },
  ],
  BUSINESSREQUIREMENTS: [
    { id: '1', name: 'Remove WAIVER before billing', legacyRuleId: '1.166' },
    { id: '2', name: 'Provider Number Missing', legacyRuleId: '1.195' },
    { id: '', name: 'Dummy business requirement id', legacyRuleId: '1.0000' },
  ],
  REPORTTYPES: [
    { id: '1', name: 'All updates in time period' },
    { id: '2', name: 'All global coding updates in time period' },
  ],
  DEPENDENCYSYSTEMS: [
    { name: 'Rule Tracker', id: '1', description: null },
    { name: 'Jira', id: '2', description: null },
    { name: 'Atlas', id: '3', description: null },
  ],
  DEPENDENCIES: [
    {
      deploymentDate: '09/03/2020',
      dependencyName: 'Service date required',
      dependencyId: '3',
      dependencySystemId: '3',
      statusName: 'In Production',
      activeWorkflowStepId: '3',
    },
  ],
  USERPERMISSIONS: ['task.update', 'document.create'],
  ATTACHMENTTYPES: [
    { name: 'Local Rule Authorization', id: '1', description: null },
    { name: 'Payer Documentation', id: '2', description: null },
    { name: 'Data Support', id: '3', description: null },
    { name: 'Athenanet Screenshot', id: '4', description: null },
    { name: 'Client clarification', id: '5', description: null },
  ],
  ATTACHMENTS: [
    {
      attachmentName: 'Payer Documentation',
      attachmentTypeId: '2',
      createdBy: 'nsenthilkumar',
      description: 'Some',
      fileName: 'Google',
      filePath: 'www.google.com',
      id: '90',
      taskId: '43',
      version: '2',
    },
  ],
  TIMEENTRYLOGS: [
    {
      created: '03/29/2021',
      createdBy: 'bvenkatesan',
      id: '14817',
      spentOn: '03/29/2021',
      spentTimeInMins: '45',
      taskId: '2093',
      taskStepId: '14653',
      totalSpentTimeInMins: '45',
      version: '1',
      workflowStepId: '1',
      workflowStepName: 'Analyze Task',
    },
  ],
  USERCOMMENTS: [
    {
      content: '<p>Test  comment</p>',
      created: '03/30/2021',
      createdBy: 'bvenkatesan',
      createdTimestamp: '03/30/2021 02:37:22',
      id: '8624',
      taskId: '2093',
    },
  ],
  DEPARTMENTORIGINS: [
    { id: '1', name: 'ACCT MGT' },
    { id: '2', name: 'CLAIM RES' },
    { id: '3', name: 'PAYER TRANSACTIONS' },
    { id: '4', name: 'CSC' },
    { id: '5', name: 'ANALYTICS' },
  ],
  BRUPDATEREASONS: [
    { id: '1', name: 'Bug fix', taskTypeIds: '1,2' },
    { id: '2', name: 'Client request', taskTypeIds: '1,2,3,4,5,6,' },
  ],
  DEPLOYMENTSTATUSES: [
    { id: '1', name: 'Success' },
    { id: '2', name: 'SmartsFailureheet' },
    { id: '3', name: 'In Progress' },
  ],
  MIGRATIONRULESLIST: {
    limit: 'ALL',
    total: '7',
    result: [
      {
        comment: null,
        contextId: '1',
        migrationStatus: 'Dual Maintenance',
        id: '54',
        businessRequirementId: null,
        ruleId: '580',
      },
      {
        comment: 'Global Rules that adhere only to ANSI 4010 and 4010A',
        contextId: '1',
        migrationStatus: 'Rule Rationalization',
        id: '1012',
        businessRequirementId: null,
        ruleId: '5817',
      },
      {
        comment:
          'Last fired: Prior to 2014. This rule supports an old Enrollment workflow using the previx "PEND*" to trigger hold rules like this one. This workflow is no longer used.',
        contextId: '1',
        migrationStatus: 'Rule Rationalization',
        id: '4317',
        businessRequirementId: null,
        ruleId: '5831',
      },
      {
        comment:
          'Rules that cater to claim formats that are either deleted/expired or not used in Billing Batch for the past 2 years',
        contextId: '1',
        migrationStatus: 'Rule Rationalization',
        id: '1069',
        businessRequirementId: null,
        ruleId: '584',
      },
      {
        comment: 'Global Rules that adhere only to ANSI 4010 and 4010A',
        contextId: '1',
        migrationStatus: 'Rule Rationalization',
        id: '1013',
        businessRequirementId: null,
        ruleId: '5856',
      },
      {
        comment: 'End-dated in 2013.',
        contextId: '1',
        migrationStatus: 'Rule Rationalization',
        id: '3',
        businessRequirementId: null,
        ruleId: '587',
      },
      {
        comment: 'Global Rules that adhere only to ANSI 4010 and 4010A',
        contextId: '1',
        migrationStatus: 'Rule Rationalization',
        id: '1014',
        businessRequirementId: null,
        ruleId: '5891',
      },
    ],
    offset: '0',
  },
  RATIONALIZATIONRULES: {
    limit: 'ALL',
    total: '3661',
    result: [
      {
        createdBy: 'COLRNR-2512_20200813',
        reviewerComments: 'End-dated in 2013.',
        rationalizationType: 'Rule Rationalization',
        rtTaskId: '132298',
        ordering: '10',
        contextId: '1',
        id: '3',
        scrubType: 'CLAIM',
        reviewedBy: 'Sofia Karabasevic',
        rtTaskStatus: 'COMPLETED',
        deleted: null,
        ruleId: '587',
        created: '08/13/2020',
        ruleType: 'Global',
        deletedBy: null,
        pattern: 'Global - End Dated Rules - Slice 1',
        lastModified: '06/22/2021',
        lastModifiedBy: 'vsivachandran',
      },
    ],
    offset: '0',
  },
};
export const DEPLOYMOCKDATA = {
  verifiedYn: null,
  tasks: [
    {
      legacyRuleId: '1.200',
      businessRequirementName: 'Add Attachment Stub',
      name: 'test2',
      id: '69',
      businessRequirementId: '85',
    },
  ],
  statusId: '1',
  version: '2',
  decisionServiceName: 'claims service',
  name: null,
  branchName: 'atlas-testing',
  logs:
    '{"DOWNLOADINFO":{"ORDER":4,"NAME":"Generate build and download archive from Decision Center","STATUS":"SUCCESS","RESPONSE":"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\\n                                 Dload  Upload   Total   Spent    Left  Speed\\n\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0\\r  6 3094k    6  190k    0     0  18397      0  0:02:52  0:00:10  0:02:42 43484\\r100 3094k  100 3094k    0     0   288k      0  0:00:10  0:00:10 --:--:--  862k\\n","MESSAGE":"Downloaded ruleapp archive at \\/tmp\\/ADT-_collector_rules2_workflow_api_v1_deployment_deploy-YG2wrArOGSwAALVH9wUAAAAD-dev105.athenahealth.com-46407_xCplV6ReV0Us7CxP","REQUEST":"curl -u \'$username:$password\' -X GET --header \'Accept: application\\/octet-stream\' \'https:\\/\\/odmdc.dev.claimrules.aws.athenahealth.com\\/decisioncenter-api\\/v1\\/deployments\\/544c395f-f462-49e2-ae0d-27ac595b5d06\\/download?baselineId=81b450f8-3c18-4e75-96e2-215fa771efa5&includeXOMInArchive=true\' --output \'\\/tmp\\/ADT-_collector_rules2_workflow_api_v1_deployment_deploy-YG2wrArOGSwAALVH9wUAAAAD-dev105.athenahealth.com-46407_xCplV6ReV0Us7CxP\\/claims-service.jar\'"},"UPLOADINFOEAST":{"ORDER":5,"NAME":"Upload to RES in Prod-East","STATUS":"SUCCESS","RESPONSE":{"resource":[{"resultPath":"\\/premruleapp\\/1.0","operationType":"UPDATE","initialPath":"\\/premruleapp\\/1.0"},{"resultPath":"\\/premruleapp\\/1.0\\/scrubnewclaim\\/1.102","managedXomGeneratedProperty":"reslib:\\/\\/premruleapp_1.0\\/1.3,","operationType":"CHANGE_VERSION_AND_ADD","initialPath":"\\/premruleapp\\/1.0\\/scrubnewclaim\\/1.0"},{"resultPath":"\\/premruleapp_1.0\\/1.3","operationType":"ALREADY_PRESENT","type":"LIB","initialPath":"\\/premruleapp_1.0\\/1.0"}],"succeeded":true},"MESSAGE":"Ruleapp version updated from \\/premruleapp\\/1.0\\/scrubnewclaim\\/1.0 to \\/premruleapp\\/1.0\\/scrubnewclaim\\/1.102","REQUEST":"curl -s -u \'$username:$password\' --header \'Content-Type:application\\/octet-stream\' --header \'X-File-Name:claims-service.jar\' --header \'X-Requested-With:XMLHttpRequest\' --data-binary \'\\\\@\\/tmp\\/ADT-_collector_rules2_workflow_api_v1_deployment_deploy-YG2wrArOGSwAALVH9wUAAAAD-dev105.athenahealth.com-46407_xCplV6ReV0Us7CxP\\/claims-service.jar\' -X POST \'https:\\/\\/odmds.dev.claimrules.aws.athenahealth.com\\/res\\/api\\/v1\\/ruleapps?accept=application%2Fjson\'"},"DEPLOYMENTINFO":{"ORDER":3,"NAME":"Fetch Deployment info from Decision Center","STATUS":"SUCCESS","RESPONSE":{"ruleAppName":"premruleapp","internalId":"dsm.Deployment:392:394","name":"DEV_Prem","description":null,"production":false,"id":"544c395f-f462-49e2-ae0d-27ac595b5d06","ruleAppVersion":"1.0","snapshotMode":"Never"},"MESSAGE":"Received Deployment id as 544c395f-f462-49e2-ae0d-27ac595b5d06","REQUEST":"curl -u \'$username:$password\' -X GET --header \'Accept: application\\/json\' \'https:\\/\\/odmdc.dev.claimrules.aws.athenahealth.com\\/decisioncenter-api\\/v1\\/decisionservices\\/a84acd90-909e-4c74-90e0-ffb677a9fa77\\/deployments?baselineId=81b450f8-3c18-4e75-96e2-215fa771efa5\'"},"DECISIONSERVICEINFO":{"ORDER":1,"NAME":"Fetch Decisionservice info from Decision center","STATUS":"SUCCESS","RESPONSE":{"internalId":"brm.RuleProject:29:29","name":"claims service","id":"a84acd90-909e-4c74-90e0-ffb677a9fa77","buildMode":"DecisionEngine"},"MESSAGE":"Received Decision Service name as claims service","REQUEST":"curl -u \'$username:$password\' -X GET --header \'Accept: application\\/json\' \'https:\\/\\/odmdc.dev.claimrules.aws.athenahealth.com\\/decisioncenter-api\\/v1\\/decisionservices\\/q=name%3Aclaims%20service\'"},"BRANCHINFO":{"ORDER":2,"NAME":"Fetch Branch info from Decision center","STATUS":"SUCCESS","RESPONSE":{"kind":"Branch","internalId":"brm.Branch:25394:25394","parentId":"4af95053-d77b-4872-bf09-1e5798d5a55b","documentation":"atlas-testing","name":"atlas-testing","id":"81b450f8-3c18-4e75-96e2-215fa771efa5","buildMode":"DecisionEngine","main":false},"MESSAGE":"Received branch name as atlas-testing","REQUEST":"curl -u \'$username:$password\' -X GET --header \'Accept: application\\/json\' \'https:\\/\\/odmdc.dev.claimrules.aws.athenahealth.com\\/decisioncenter-api\\/v1\\/decisionservices\\/a84acd90-909e-4c74-90e0-ffb677a9fa77\\/branches\'"}}',
  description: null,
  dcUrl: 'https://odmdc.dev.claimrules.aws.athenahealth.com/decisioncenter-api',
  deploymentConfigName: 'DEV_Prem',
  releaseVersion: null,
  id: '87',
  envs: [
    {
      statusId: '1',
      resUrl: 'https://odmds.dev.claimrules.aws.athenahealth.com',
      version: '2',
      name: 'Prod-East',
      resultVersion: '1.102',
      id: '67',
      initialVersion: '1.0',
    },
  ],
};
