import { TaskDetail } from '../../types';

export const TaskDetailsMockData1: TaskDetail = {
  originatingSystemId: '1',
  originatingSystemName: 'SaleForce',
  statusId: '3',
  dueDate: '10/10/2020',
  status: 'Assigned',
  createdBy: 'vsivachandran',
  contextId: '',
  contextName: '',
  contextRefId: '',
  ruleReportingCategoryId: null,
  businessRequirementId: '6',
  originatingCaseId: '123',
  clientDueDate: '11/11/2020',
  modelDesignChanges: null,
  localRuleUseCaseId: null,
  id: '26',
  activeTaskStepId: '61',
  activeWorkflowStepId: '5',
  businessRequirementTypeId: null,
  priorityName: 'P0',
  dtChangesYn: null,
  legacyRuleId: '1.122',
  businessRequirementName: 'Service date required',
  name: 'test with axios',
  taskTypeId: '3',
  priorityId: '1',
  description: null,
  version: '2',
  jiraId: 'COLRDD-9876',
  legacyTaskId: 'LT-098',
  legacyRuleArchived: '07/07/2020',
  taskTypeName: 'Dual update',
  deploymentDate: '07/09/2020',
  modelBranchUrl: 'http://model.com',
  dtBranchUrl: 'http://model.com',
  escalatedYn: 'Y',
  canSignOff: '1',
  rules2TransformationStatusId: 1,
  departmentOriginId: 1,
  departmentOriginName: '',
  taskDependencies: [],
  taskDecisionTableDetails: [
    {
      description: '',
      id: '123',
      lastModifiedBy: '',
      modelName: 'test model name',
      name: 'test name',
      ordering: '',
      refId: '1',
      refUrl: 'http://test.com',
      taskId: '8',
      version: '1',
    },
  ],
  taskSteps: [
    {
      workflowStepId: '1',
      signOffStatement: 'My analysis is complete',
      version: '5',
      signedOffYn: 'Y',
      name: 'Analyze Task',
      teamId: '1',
      ordering: '1',
      transitionText: 'Send for Initial Review',
      id: '57',
      assignedTo: 'vsivachandran',
      plannedCompletion: '01/01/2000',
      actualCompletion: '01/01/2000',
      totalWorkLog: '30',
    },
    {
      workflowStepId: '2',
      signOffStatement: 'My review is complete',
      version: '3',
      signedOffYn: 'Y',
      name: 'Review Task',
      teamId: '2',
      ordering: '2',
      transitionText: 'Send for Manager Review',
      id: '58',
      assignedTo: 'vsivachandran',
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
    {
      workflowStepId: '3',
      signOffStatement: 'My review is complete',
      version: '3',
      signedOffYn: 'Y',
      name: 'Manager Review',
      teamId: '3',
      ordering: '3',
      transitionText: 'Send for Model Changes',
      id: '59',
      assignedTo: 'vsivachandran',
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
    {
      workflowStepId: '4',
      signOffStatement: 'My model changes are complete',
      version: '3',
      signedOffYn: 'Y',
      name: 'Make Model Changes',
      teamId: '4',
      ordering: '4',
      transitionText: 'Send for Code Changes',
      id: '60',
      assignedTo: 'vsivachandran',
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
    {
      workflowStepId: '5',
      signOffStatement: 'My code changes are complete',
      version: '2',
      signedOffYn: null,
      name: 'Make Code Changes',
      teamId: '5',
      ordering: '5',
      transitionText: 'Send for Testing',
      id: '61',
      assignedTo: 'ADMDevicesBangalore',
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
    {
      workflowStepId: '6',
      signOffStatement: 'My testing is complete',
      version: '1',
      signedOffYn: null,
      name: 'Test Changes',
      teamId: '6',
      ordering: '6',
      transitionText: 'Send for Final Review',
      id: '62',
      assignedTo: null,
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
    {
      workflowStepId: '7',
      signOffStatement:
        'My review is complete and changes are ready for deployment',
      version: '1',
      signedOffYn: null,
      name: 'Review Changes',
      teamId: '7',
      ordering: '7',
      transitionText: 'Send for Deploying Changes',
      id: '63',
      assignedTo: null,
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
    {
      workflowStepId: '8',
      signOffStatement: 'Deployment is complete and changes are in-production',
      version: '1',
      signedOffYn: null,
      name: 'Deploy Changes',
      teamId: '8',
      ordering: '8',
      transitionText: 'Deployment Complete',
      id: '64',
      assignedTo: null,
      plannedCompletion: null,
      actualCompletion: null,
      totalWorkLog: '30',
    },
  ],
  created: '07/02/2020',
  lastModified: '07/02/2020',
  businessRequirementDesc: null,
  athenaNetChangesYn: null,
  lastModifiedBy: 'vsivachandran',
  testClaimExample: 'testClaim',
  testNote: 'atestnote',
  associatedBRTasks: [],
  ruleTypeId: '1',
  ruleEngineId: '1',
  visitRuleDisplayLocationId: '1',
  internalFixText1: '',
  internalFixText2: '',
  brUpdateReasonIds: ['1'],
  brUpdateReasons: [],
  claimRuleCategoryId: '1',
  scrubTypeId: '1',
  claimRuleCategoryRefId: '1',
  claimRuleCategory: 'test',
  rtSynchronizationLog: {
    rtTaskCreationStatusId: '2',
    rtTaskId: null,
    id: '2',
    taskId: '1',
    version: '1',
  },
  priorityReasonId: '1',
  priorityReason: 'Go Live Critical',
  priorityReasonNote: 'note1',
  rejectionReason: '',
  rejectionDescription: '',
};

export const TaskDetailsMockData2: TaskDetail = {
  originatingSystemId: '',
  statusId: '3',
  dueDate: null,
  status: 'Assigned',
  createdBy: 'vsivachandran',
  contextId: '',
  contextName: '',
  contextRefId: '',
  ruleReportingCategoryId: null,
  businessRequirementId: '6',
  originatingSystemName: 'SaleForce',
  originatingCaseId: '',
  clientDueDate: '',
  modelDesignChanges: null,
  localRuleUseCaseId: null,
  id: '',
  activeTaskStepId: '101',
  activeWorkflowStepId: '1',
  businessRequirementTypeId: null,
  priorityName: 'P0',
  dtChangesYn: null,
  legacyRuleId: '',
  businessRequirementName: 'Service date required',
  name: 'test with axios',
  taskTypeId: '3',
  priorityId: '',
  description: null,
  version: '2',
  jiraId: 'COLRDD-9876',
  legacyTaskId: '',
  legacyRuleArchived: '',
  taskTypeName: 'Dual update',
  deploymentDate: '',
  modelBranchUrl: 'http://model.com',
  dtBranchUrl: 'http://model.com',
  escalatedYn: 'Y',
  canSignOff: '1',
  rules2TransformationStatusId: 2,
  departmentOriginId: 2,
  taskDependencies: [],
  taskDecisionTableDetails: [
    {
      description: '',
      id: '123',
      lastModifiedBy: '',
      modelName: 'test model name',
      name: 'test name',
      ordering: '',
      refId: '1',
      refUrl: 'http://test.com',
      taskId: '8',
      version: '1',
    },
  ],
  taskSteps: [
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Analyze Task',
      ordering: '1',
      transitionText: null,
      id: '101',
      assignedTo: '',
      version: '1',
      plannedCompletion: '01/01/2000',
      actualCompletion: '01/01/2000',
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Review Task',
      ordering: '2',
      transitionText: null,
      id: '102',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Manager Review',
      ordering: '3',
      transitionText: null,
      id: '103',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Make Model Changes',
      ordering: '4',
      transitionText: null,
      id: '104',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Make Code Changes',
      ordering: '5',
      transitionText: null,
      id: '105',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Test Changes',
      ordering: '6',
      transitionText: null,
      id: '106',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Review Changes',
      ordering: '7',
      transitionText: null,
      id: '107',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
    {
      workflowStepId: null,
      signOffStatement: null,
      signedOffYn: null,
      name: 'Deploy Changes',
      ordering: '8',
      transitionText: null,
      id: '108',
      assignedTo: null,
      version: '1',
      plannedCompletion: null,
      actualCompletion: null,
    },
  ],
  created: '07/02/2020',
  lastModified: '07/02/2020',
  businessRequirementDesc: null,
  athenaNetChangesYn: null,
  lastModifiedBy: 'vsivachandran',
  testClaimExample: 'testClaim',
  testNote: 'atestnote',
  associatedBRTasks: [],
  ruleTypeId: '1',
  ruleEngineId: '1',
  visitRuleDisplayLocationId: '1',
  internalFixText1: '',
  internalFixText2: '',
  departmentOriginName: '',
  brUpdateReasonIds: ['2'],
  brUpdateReasons: [],
  claimRuleCategoryId: '1',
  scrubTypeId: '1',
  claimRuleCategoryRefId: '1',
  claimRuleCategory: 'test',
  rtSynchronizationLog: {
    rtTaskCreationStatusId: '2',
    rtTaskId: null,
    id: '2',
    taskId: '1',
    version: '1',
  },
  priorityReasonId: '1',
  priorityReason: 'Go Live Critical',
  priorityReasonNote: 'note1',
  rejectionReason: '',
  rejectionDescription: '',
};

export const TaskDetailsMockData3: TaskDetail = {
  originatingSystemName: 'SaleForce',
  originatingSystemId: '',
  statusId: '3',
  dueDate: null,
  status: 'Assigned',
  createdBy: 'vsivachandran',
  contextId: '',
  contextName: '',
  contextRefId: '',
  ruleReportingCategoryId: null,
  businessRequirementId: '6',
  originatingCaseId: '',
  clientDueDate: '',
  modelDesignChanges: null,
  localRuleUseCaseId: null,
  id: '',
  activeTaskStepId: '101',
  activeWorkflowStepId: '1',
  businessRequirementTypeId: null,
  priorityName: 'P0',
  dtChangesYn: null,
  legacyRuleId: '',
  businessRequirementName: 'Service date required',
  name: 'test with axios',
  taskTypeId: '3',
  priorityId: '',
  description: null,
  version: '2',
  jiraId: 'COLRDD-9876',
  legacyTaskId: '',
  legacyRuleArchived: '',
  taskTypeName: 'Dual update',
  deploymentDate: '07/09/2020',
  taskSteps: [],
  created: '07/02/2020',
  lastModified: '07/02/2020',
  businessRequirementDesc: null,
  athenaNetChangesYn: null,
  lastModifiedBy: 'vsivachandran',
  testClaimExample: 'testClaim',
  testNote: 'atestnote',
  modelBranchUrl: 'http://model.com',
  dtBranchUrl: 'http://model.com',
  escalatedYn: 'Y',
  canSignOff: '1',
  rules2TransformationStatusId: 3,
  departmentOriginId: 3,
  taskDependencies: [],
  taskDecisionTableDetails: [
    {
      description: '',
      id: '123',
      lastModifiedBy: '',
      modelName: 'test model name',
      name: 'test name',
      ordering: '',
      refId: '1',
      refUrl: 'http://test.com',
      taskId: '8',
      version: '1',
    },
  ],
  associatedBRTasks: [
    {
      id: '153',
      name: 'name',
      activeTaskStepId: '1',
      activeTaskStepName: 'name',
    },
  ],
  ruleTypeId: '1',
  ruleEngineId: '1',
  visitRuleDisplayLocationId: '1',
  internalFixText1: '',
  internalFixText2: '',
  departmentOriginName: '',
  brUpdateReasonIds: ['1', '2'],
  brUpdateReasons: [],
  claimRuleCategoryId: '1',
  scrubTypeId: '1',
  claimRuleCategoryRefId: '1',
  claimRuleCategory: 'test',
  rtSynchronizationLog: {
    rtTaskCreationStatusId: '3',
    rtTaskId: null,
    id: '2',
    taskId: '1',
    version: '1',
  },
  priorityReasonId: '1',
  priorityReason: 'Go Live Critical',
  priorityReasonNote: 'note1',
  rejectionReason: '',
  rejectionDescription: '',
};
